### ISSUE TITLE
Can't install on Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [addiks/gedit-gitmenu#1]
When trying to use the plugin on Ubuntu 16.04 I got the following errors:

```
gedit
Traceback (most recent call last):
  File "/home/ulrith/.local/share/gedit/plugins/gedit-gitmenu-master/addiks-gitmenu.py", line 35, in do_activate
    self._init_gitmenu()
  File "/home/ulrith/.local/share/gedit/plugins/gedit-gitmenu-master/addiks-gitmenu.py", line 41, in _init_gitmenu
    manager = self.window.get_ui_manager()
AttributeError: 'Window' object has no attribute 'get_ui_manager'
Traceback (most recent call last):
  File "/home/ulrith/.local/share/gedit/plugins/gedit-gitmenu-master/addiks-gitmenu.py", line 70, in do_update_state
    self._gitAction.set_visible(False)
AttributeError: 'AddiksGitMenuWindow' object has no attribute '_gitAction'

```

**Comment by addiks** [comment]
I just pushed a new version with (hopefully) better support for gedit-3.12+. Please test on the new version again and report back if it works for you.

**Comment by ghost** [comment]
Thank you, now it's working
